{"name": "test_login[0123456789-Vietmy1204@-wrong_phone]", "status": "passed", "steps": [{"name": "Attempting login with phone: 0123456789, password: Vietmy1204@", "status": "passed", "start": 1754560518820, "stop": 1754560531928}, {"name": "Verify error message for wrong phone number", "status": "passed", "attachments": [{"name": "Error Message", "source": "d6db14a4-8d07-4077-87ae-cc2c32f2438f-attachment.txt", "type": "text/plain"}], "start": 1754560531928, "stop": 1754560531976}], "parameters": [{"name": "phone", "value": "'0123456789'"}, {"name": "password", "value": "'Vietmy1204@'"}, {"name": "expected_result", "value": "'wrong_phone'"}], "start": 1754560518820, "stop": 1754560531976, "uuid": "018447ab-cee2-45b1-86c2-4904809dc4ab", "historyId": "4c4b3c34dd03d5a8603aefc32b6bb470", "testCaseId": "736e2521b0951c3628ea00f9e70dcc7b", "fullName": "tests.test_01_login#test_login", "labels": [{"name": "feature", "value": "Login Functionality"}, {"name": "story", "value": "Test login with valid and invalid credentials"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_01_login"}, {"name": "host", "value": "pnvl161"}, {"name": "thread", "value": "7372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_01_login"}], "titlePath": ["tests", "test_01_login.py"]}